version: '3.9'

services:
  movies-api:
    build: .
    restart: always
    ports:
      - 5050:5050
    depends_on:
      - maria_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'

  maria_db:
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: movies
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: wp